extends RefCounted
## Generated by content build. Edit content/accepted/catalog.json, not this file.
const VERSION: int = 1
const CONTENT_HASH: String = "4d2f62a1870387678981ed6135e3816f2bce43f535dea0f912c7af961b27059b"
const CARD_COUNT: int = 30
const ROWS: Array[Dictionary] = [
    {"id":0,"element":0,"ru":"Искра","en":"Spark","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":1,"element":0,"ru":"Пламя","en":"Flame","cost":2,"attack":1,"health":4,"role":1,"kind":"guard"},
    {"id":2,"element":1,"ru":"Капля","en":"Drop","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":3,"element":1,"ru":"Прилив","en":"Tide","cost":2,"attack":2,"health":3,"role":2,"kind":"lancer"},
    {"id":4,"element":2,"ru":"Разряд","en":"Bolt","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":5,"element":2,"ru":"Гроза","en":"Storm","cost":2,"attack":2,"health":2,"role":3,"kind":"archer"},
    {"id":6,"element":3,"ru":"Ветер","en":"Breeze","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":7,"element":3,"ru":"Вихрь","en":"Gust","cost":2,"attack":2,"health":2,"role":4,"kind":"flanker"},
    {"id":8,"element":4,"ru":"Камень","en":"Stone","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":9,"element":4,"ru":"Скала","en":"Rock","cost":2,"attack":1,"health":4,"role":1,"kind":"guard"},
    {"id":10,"element":5,"ru":"Луч","en":"Ray","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":11,"element":5,"ru":"Светоч","en":"Beacon","cost":2,"attack":2,"health":3,"role":2,"kind":"lancer"},
    {"id":12,"element":6,"ru":"Тень","en":"Shade","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":13,"element":6,"ru":"Мрак","en":"Gloom","cost":2,"attack":2,"health":2,"role":3,"kind":"archer"},
    {"id":14,"element":7,"ru":"Дрон","en":"Drone","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":15,"element":7,"ru":"Титан","en":"Titan","cost":2,"attack":2,"health":2,"role":4,"kind":"flanker"},
    {"id":16,"element":8,"ru":"Спора","en":"Spore","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":17,"element":8,"ru":"Токсин","en":"Toxin","cost":2,"attack":1,"health":4,"role":1,"kind":"guard"},
    {"id":18,"element":9,"ru":"Шёпот","en":"Whisper","cost":1,"attack":1,"health":2,"role":0,"kind":"fighter"},
    {"id":19,"element":9,"ru":"Загадка","en":"Enigma","cost":2,"attack":2,"health":3,"role":2,"kind":"lancer"},
    {"id":20,"element":0,"ru":"Ифрит","en":"Ifrit","cost":4,"attack":4,"health":5,"role":0,"kind":"fighter"},
    {"id":21,"element":1,"ru":"Хранитель глубин","en":"Deep Guardian","cost":5,"attack":3,"health":8,"role":1,"kind":"guard"},
    {"id":22,"element":2,"ru":"Громовержец","en":"Thunderlord","cost":5,"attack":4,"health":5,"role":2,"kind":"lancer"},
    {"id":23,"element":3,"ru":"Небесный охотник","en":"Sky Hunter","cost":6,"attack":4,"health":4,"role":3,"kind":"archer"},
    {"id":24,"element":4,"ru":"Обсидиановый страж","en":"Obsidian Warden","cost":4,"attack":3,"health":5,"role":4,"kind":"flanker"},
    {"id":25,"element":5,"ru":"Архонт","en":"Archon","cost":4,"attack":4,"health":5,"role":0,"kind":"fighter"},
    {"id":26,"element":6,"ru":"Владыка теней","en":"Shadow Lord","cost":5,"attack":3,"health":8,"role":1,"kind":"guard"},
    {"id":27,"element":7,"ru":"Осадный титан","en":"Siege Titan","cost":5,"attack":4,"health":5,"role":2,"kind":"lancer"},
    {"id":28,"element":8,"ru":"Чумной колосс","en":"Plague Colossus","cost":6,"attack":4,"health":4,"role":3,"kind":"archer"},
    {"id":29,"element":9,"ru":"Сфинкс","en":"Sphinx","cost":4,"attack":3,"health":5,"role":4,"kind":"flanker"}
]

static func card(id: int) -> Dictionary:
    return ROWS[id].duplicate(true) if id >= 0 and id < CARD_COUNT else {}
