import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  canonical,
  digest,
  inputKey,
  expectedCases,
  pngSize,
  assertCapture,
  assertManifest,
  safeFile
} from '../scripts/gallery-policy.mjs';
const nonce = 'a'.repeat(32),
  sha = 'b'.repeat(64);
function png(width, height, index = 0) {
  const data = Buffer.alloc(100);
  Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).copy(data);
  data.writeUInt32BE(13, 8);
  data.write('IHDR', 12);
  data.writeUInt32BE(width, 16);
  data.writeUInt32BE(height, 20);
  data[30] = index;
  return data;
}
function fixture() {
  const bytes = new Map(),
    inputs = [{ path: 'game/src/main.gd', sha256: sha }];
  const capture = {
    schemaVersion: 1,
    nonce,
    sourcePreview: true,
    installedApkCapture: false,
    personalProfileUntouched: true,
    renderer: 'Windows',
    images: expectedCases().map((c, i) => {
      const b = png(c.width, c.height, i);
      bytes.set(c.id, b);
      return { ...c, file: c.id + '.png', sha256: digest(b), sampledColors: 16 };
    })
  };
  const key = inputKey(inputs),
    assets = capture.images.map((i) => ({
      id: i.id,
      path: `docs/media/gallery/${key}/${nonce}/${i.file}`,
      sha256: i.sha256
    }));
  const manifest = {
    schemaVersion: 1,
    repository: 'neurofoxpro/multimental',
    captureBaseCommit: '1'.repeat(40),
    captureWorktreeDirty: true,
    sourceIdentity: 'canonical-render-inputs-excluding-ci-build-stamp',
    inputKey: key,
    inputs,
    nonce,
    capture,
    assets
  };
  return {
    capture,
    manifest,
    inputs,
    read: (p) => bytes.get(assets.find((a) => a.path === p)?.id)
  };
}
test('expected matrix contains twenty portrait and four landscape real views', () => {
  assert.equal(expectedCases().length, 24);
  assert.equal(new Set(expectedCases().map((c) => c.id)).size, 24);
});
test('Windows line endings are canonical, real contents remain different', () => {
  assert.equal(
    digest(canonical(Buffer.from('a\r\nb\r\n'), 'x.gd')),
    digest(canonical(Buffer.from('a\nb\n'), 'x.gd'))
  );
  assert.notEqual(
    digest(canonical(Buffer.from('a\nb\n'), 'x.gd')),
    digest(canonical(Buffer.from('b\na\n'), 'x.gd'))
  );
});
test('valid manifest verifies every image hash and dimensions', () => {
  const f = fixture();
  assert.equal(assertManifest(f.manifest, f.inputs, f.read), true);
});
for (const [name, change] of [
  ['missing stage', (c) => c.images.pop()],
  ['duplicate stage', (c) => (c.images[1] = c.images[0])],
  ['wrong viewport', (c) => (c.images[0].width = 360)],
  ['blank observation', (c) => (c.images[0].sampledColors = 1)],
  ['headless dummy', (c) => (c.renderer = 'headless')],
  ['personal data written', (c) => (c.personalProfileUntouched = false)],
  ['claims installed APK', (c) => (c.installedApkCapture = true)],
  ['wrong capture id', (c) => (c.nonce = 'x')],
  ['unsafe filename', (c) => (c.images[0].file = '../../x.png')]
])
  test('capture refuses ' + name, () => {
    const f = fixture();
    change(f.capture);
    assert.throws(() => assertCapture(f.capture, nonce));
  });
test('changed source, image bytes, dimensions and outside target fail', () => {
  const f = fixture();
  assert.throws(() =>
    assertManifest(f.manifest, [{ ...f.inputs[0], sha256: 'c'.repeat(64) }], f.read)
  );
  assert.throws(() => assertManifest(f.manifest, f.inputs, () => png(1, 1)));
  const g = fixture();
  g.manifest.assets[0].path = 'other.png';
  assert.throws(() => assertManifest(g.manifest, g.inputs, g.read));
});
test('header validation rejects non-PNG and truncated data', () => {
  assert.throws(() => pngSize(Buffer.alloc(1)));
  assert.throws(() => pngSize(Buffer.alloc(100)));
});
for (const p of ['../secret', '/tmp/a', 'x//y', 'x/./y', 'x\\y', '.git/../x'])
  test('unsafe asset path ' + p, () => assert.throws(() => safeFile(process.cwd(), p)));
test('safe path refuses symlink parents', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gallery-policy-'));
  try {
    fs.mkdirSync(path.join(root, 'real'));
    try {
      fs.symlinkSync(path.join(root, 'real'), path.join(root, 'link'), 'junction');
    } catch (e) {
      if (e.code === 'EPERM') {
        t.skip('symlink creation is not permitted');
        return;
      }
      throw e;
    }
    assert.throws(() => safeFile(root, 'link/image.png'));
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

import { managedReplacement } from '../scripts/gallery-policy.mjs';
test('only exact prior generated bytes may replace a dirty document', () => {
  assert.equal(managedReplacement(sha, true, []), null);
  assert.equal(managedReplacement(sha, false, [sha]), sha);
  assert.throws(() => managedReplacement(sha, false, []));
  assert.throws(() => managedReplacement('c'.repeat(64), false, [sha]));
  assert.throws(() => managedReplacement(sha, false, ['not-a-hash']));
});
test('half-applied document pair accepts only the two journaled generations', () => {
  const next = 'c'.repeat(64);
  assert.equal(managedReplacement(sha, false, [sha, next]), sha);
  assert.equal(managedReplacement(next, false, [sha, next]), next);
  assert.throws(() => managedReplacement('d'.repeat(64), false, [sha, next]));
});
test('same screenshot reused for a different page is rejected', () => {
  const f = fixture();
  f.capture.images[1].sha256 = f.capture.images[0].sha256;
  assert.throws(() => assertCapture(f.capture, nonce));
});

import {
  README_START,
  README_END,
  readmeGallery,
  replaceReadmeGallery
} from '../scripts/gallery-policy.mjs';
test('README preview changes only its managed block and is idempotent', () => {
  const f = fixture(),
    prefix = '# Hand edited intro\n',
    suffix = '\nPersonal documentation\n';
  const block = readmeGallery(f.manifest),
    before = prefix + README_START + '\nold\n' + README_END + suffix;
  const after = replaceReadmeGallery(before, block);
  assert.equal(after, prefix + block + suffix);
  assert.equal(replaceReadmeGallery(after, block), after);
  assert.throws(() => replaceReadmeGallery(before + README_START, block));
  assert.throws(() => replaceReadmeGallery('no markers', block));
  assert.throws(() => replaceReadmeGallery('\u0007' + before, block));
});
