import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {readJSON,writeJSON,sha,context,gate} from '../skills/game-production/scripts/lib.mjs';
const root=process.cwd(),p=readJSON('.gameprod/project.json');context(root,p);if(!gate(root,p,'verified').ok)throw Error('Verify exact tooling before deployment');
const r=spawnSync('git',['rev-parse','HEAD'],{encoding:'utf8'});if(r.status!==0)throw Error('Git required');const commit=r.stdout.trim();const dirty=spawnSync('git',['status','--porcelain'],{encoding:'utf8'});if(dirty.stdout.trim())throw Error('Commit reviewed changes before deploying agent');
const work=path.dirname(root),configFile=path.join(work,'station.local.json'),config=readJSON(configFile);if(config.repository!==p.repository||!p.authorizedHosts.includes(config.allowedHost))throw Error('Station mismatch');
const destination=path.join(work,'agent-'+commit.slice(0,12));const files=['scripts/update-device.mjs','scripts/install-device.mjs','scripts/device-readiness.mjs','scripts/device-launch.mjs','scripts/register-updater.ps1','skills/game-production/scripts/lib.mjs'];const inventory=files.map(file=>({file,sha256:sha(fs.readFileSync(file))}));
if(fs.existsSync(destination)){const old=readJSON(path.join(destination,'manifest.json'));if(JSON.stringify(old.files)!==JSON.stringify(inventory))throw Error('Different installed agent in target');}else{for(const {file}of inventory){const dst=path.join(destination,file);fs.mkdirSync(path.dirname(dst),{recursive:true});fs.copyFileSync(file,dst,fs.constants.COPYFILE_EXCL);}writeJSON(path.join(destination,'manifest.json'),{repository:p.repository,commit,files:inventory});}
for(const {file,sha256}of inventory)if(sha(fs.readFileSync(path.join(destination,file)))!==sha256)throw Error('Installed script altered');
const record=path.join(work,'agent-deployments');fs.mkdirSync(record,{recursive:true});writeJSON(path.join(record,commit+'.local.json'),{at:new Date().toISOString(),oldConfig:config,agent:destination,files:inventory});
config.autoCloseForUpdate=true;config.allowedPermissions=[...new Set([...(config.allowedPermissions||[]),'android.permission.BLUETOOTH_CONNECT'])];config.reviewedSourceCommit=commit;writeJSON(configFile,config);
const script=path.join(destination,'scripts/update-device.mjs');const action='"'+script+'" --config "'+configFile+'"';
const ps=String.raw`$ErrorActionPreference='Stop';$task=Get-ScheduledTask -TaskName 'Multimental-Dev-APK-Updater';if($task.Actions.Execute -notlike '*node.exe' -or $task.Actions.Arguments -notlike '*MultimentalWork*update-device.mjs*'){throw 'Unexpected existing task'};$a=New-ScheduledTaskAction -Execute $env:MULTIMENTAL_NODE -Argument $env:MULTIMENTAL_ACTION -WorkingDirectory $env:MULTIMENTAL_CWD;Set-ScheduledTask -TaskName $task.TaskName -Action $a | Out-Null;Enable-ScheduledTask -TaskName $task.TaskName | Out-Null;Get-ScheduledTask -TaskName $task.TaskName | Select-Object TaskName,State`;
const applied=spawnSync('powershell.exe',['-NoProfile','-Command',ps],{encoding:'utf8',timeout:30000,env:{...process.env,MULTIMENTAL_NODE:process.execPath,MULTIMENTAL_ACTION:action,MULTIMENTAL_CWD:path.dirname(script)}});if(applied.status!==0)throw Error('Task update failed: '+applied.stderr);console.log(applied.stdout);writeJSON('.gameprod/evidence/agent-deploy.json',{status:'passed',commit,files:inventory,autoCloseForUpdate:true});console.log('REVIEWED_AGENT_DEPLOYED '+commit.slice(0,12));
