import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {readJSON,writeJSON,sha,chooseDevice,verifyManifest} from '../skills/game-production/scripts/lib.mjs';import {waitReady} from './device-readiness.mjs';
export function exec(exe,args,{allowFailure=false,env=process.env,binary=false}={}){const r=spawnSync(exe,args,{shell:false,encoding:binary?null:'utf8',timeout:120000,maxBuffer:16*1024*1024,env});if((r.error||r.status!==0)&&!allowFailure)throw Error(path.basename(exe)+' failed: '+String(r.stderr||r.error||r.stdout||'').slice(0,500));return binary?r.stdout:String(r.stdout||'');}
export function validateConfig(c){if(!c.allowedHost||os.hostname().toUpperCase()!==c.allowedHost.toUpperCase())throw Error('Unauthorized execution host');if(!/^[-\w.]+\/[-\w.]+$/.test(c.repository)||!c.package?.endsWith('.dev')||!c.serial||!path.isAbsolute(c.workDir))throw Error('Explicit local device configuration required');for(const k of ['adb','java','keytool','apksigner','aapt'])if(!fs.existsSync(c[k]||''))throw Error('Missing local tool '+k);return c;}
export function isForeground(c){const dump=exec(c.adb,['-s',c.serial,'shell','dumpsys','activity','activities'],{allowFailure:true});return dump.split(/\r?\n/).some(l=>/mResumedActivity|topResumedActivity/.test(l)&&l.includes(c.package+'/'));}
function signer(c,input,output){const dir=path.join(c.workDir,'private-signing');fs.mkdirSync(dir,{recursive:true});const info=path.join(dir,'identity.local.json'),key=path.join(dir,'development.p12');let identity;
 if(fs.existsSync(info)){identity=readJSON(info);if(!fs.existsSync(key))throw Error('Local signing key missing; never regenerate an update identity silently');}else{if(fs.existsSync(key))throw Error('Signing identity metadata missing');identity={password:crypto.randomBytes(32).toString('hex'),created:new Date().toISOString()};const env={...process.env,MULTIMENTAL_KEY_PASS:identity.password};exec(c.keytool,['-genkeypair','-noprompt','-storetype','PKCS12','-keystore',key,'-alias','multimental-local-dev','-storepass:env','MULTIMENTAL_KEY_PASS','-keypass:env','MULTIMENTAL_KEY_PASS','-keyalg','RSA','-keysize','3072','-validity','10000','-dname','CN=Multimental Local Development'],{env});writeJSON(info,identity);}
 exec(c.java,['-jar',c.apksigner,'sign','--ks',key,'--ks-key-alias','multimental-local-dev','--ks-pass','env:MULTIMENTAL_KEY_PASS','--key-pass','env:MULTIMENTAL_KEY_PASS','--out',output,input],{env:{...process.env,MULTIMENTAL_KEY_PASS:identity.password}});
 const verify=exec(c.java,['-jar',c.apksigner,'verify','--print-certs',output]);const cert=verify.match(/certificate SHA-256 digest:\s*([a-f0-9]+)/i)?.[1]?.toLowerCase();if(!cert)throw Error('No verified certificate');if(identity.certificate&&identity.certificate!==cert)throw Error('Signing identity changed');if(!identity.certificate){identity.certificate=cert;writeJSON(info,identity);}return cert;}
export async function install(c,dir,m,{deferForeground=true,forceReinstall=false}={}){validateConfig(c);if(m.repository!==c.repository||m.package!==c.package)throw Error('Artifact scope mismatch');const original=verifyManifest(dir,m);chooseDevice(exec(c.adb,['devices','-l']),c.serial);fs.mkdirSync(c.workDir,{recursive:true});const lock=path.join(c.workDir,'install.lock');let fd;try{fd=fs.openSync(lock,'wx');}catch{throw Error('Install already in progress; inspect stale locks manually');}fs.writeFileSync(fd,JSON.stringify({pid:process.pid,started:new Date().toISOString()}));fs.closeSync(fd);
 try{const badging=exec(c.aapt,['dump','badging',original]);const pkg=badging.match(/package: name='([^']+)' versionCode='(\d+)'/);if(!pkg||pkg[1]!==c.package||Number(pkg[2])!==m.versionCode)throw Error('APK identity differs from manifest');const permissions=exec(c.aapt,['dump','permissions',original]);const grants=[...permissions.matchAll(/uses-permission(?:-sdk-\d+)?: name='([^']+)'/g)].map(x=>x[1]);const allowed=c.allowedPermissions||[];if(grants.some(x=>!allowed.includes(x)))throw Error('Unexpected Android permission');
 const stampFile=path.join(c.workDir,'installed.local.json');const previous=fs.existsSync(stampFile)?readJSON(stampFile):null;const installed=exec(c.adb,['-s',c.serial,'shell','dumpsys','package',c.package],{allowFailure:true});const version=Number(installed.match(/versionCode=(\d+)/)?.[1]||0);
 if(!forceReinstall&&previous?.originalSha256===m.sha256&&version===m.versionCode){console.log('DEVICE_UPDATE_ALREADY_CURRENT');return {status:'already_current',versionCode:version};}
 if(version>m.versionCode||previous?.versionCode>m.versionCode)throw Error('Downgrade refused');if(deferForeground&&!c.autoCloseForUpdate&&isForeground(c)){console.log('DEVICE_UPDATE_DEFERRED_FOREGROUND');return {status:'deferred_foreground'};}
 const out=path.join(dir,'local-development.apk');const certificate=signer(c,original,out);const signedHash=sha(fs.readFileSync(out));if(c.autoCloseForUpdate||!deferForeground)exec(c.adb,['-s',c.serial,'shell','am','force-stop',c.package]);const result=exec(c.adb,['-s',c.serial,'install','-r',out]);if(!/Success/.test(result))throw Error('Install did not confirm Success');
 exec(c.adb,['-s',c.serial,'shell','am','force-stop',c.package]);exec(c.adb,['-s',c.serial,'shell','monkey','-p',c.package,'-c','android.intent.category.LAUNCHER','1']);const started=performance.now();
 const ready=await waitReady({pid:()=>exec(c.adb,['-s',c.serial,'shell','pidof',c.package],{allowFailure:true}),log:id=>{const logs=exec(c.adb,['-s',c.serial,'logcat','-d','--pid='+id,'-t','400'],{allowFailure:true});fs.writeFileSync(path.join(dir,'app-logcat.local.txt'),logs);return logs;}});
 const actual=exec(c.adb,['-s',c.serial,'shell','dumpsys','package',c.package]);if(Number(actual.match(/versionCode=(\d+)/)?.[1])!==m.versionCode)throw Error('Installed version mismatch');
 if(isForeground(c)){const image=exec(c.adb,['-s',c.serial,'exec-out','screencap','-p'],{binary:true});if(image?.length)fs.writeFileSync(path.join(dir,'screenshot.local.png'),image);}
 const receipt={schemaVersion:1,status:'installed_and_launched',repository:c.repository,sourceCommit:m.commit,version:m.version,versionCode:m.versionCode,package:c.package,originalSha256:m.sha256,installedSha256:signedHash,transformation:'re-signed with persistent private local development key; CI APK preserved',certificateSha256:certificate,installedAt:new Date().toISOString(),model:exec(c.adb,['-s',c.serial,'shell','getprop','ro.product.model']).trim(),readyMarker:true,readinessWaitMs:Math.round(performance.now()-started),humanAcceptance:'pending'};writeJSON(path.join(dir,'device-receipt.json'),receipt);writeJSON(stampFile,receipt);console.log('DEVICE_INSTALL_PASS '+m.version+' '+signedHash);return receipt;
 }finally{fs.unlinkSync(lock);}}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const a=process.argv.slice(2);try{if(!a.includes('--config')||!a.includes('--dir'))throw Error('Usage: --config LOCAL_CONFIG --dir ARTIFACT_DIR');const config=a[a.indexOf('--config')+1],dir=a[a.indexOf('--dir')+1];await install(readJSON(config),path.resolve(dir),readJSON(path.join(dir,'build-manifest.json')));}catch(e){console.error('DEVICE_BLOCKED: '+e.message);process.exitCode=1;}}
