import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {readJSON,writeJSON,chooseDevice} from '../skills/game-production/scripts/lib.mjs';import {exec,install,validateConfig,isForeground} from './install-device.mjs';
export function assetURL(url,repo){const u=new URL(url);if(u.protocol!=='https:'||u.hostname!=='github.com'||!u.pathname.startsWith('/'+repo+'/releases/download/'))throw Error('Noncanonical asset URL');return u.href;}
async function json(url){const r=await fetch(url,{headers:{'User-Agent':'multimental-device-updater','Accept':'application/vnd.github+json'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('GitHub returned '+r.status);return r.json();}
async function download(url,file,max){const r=await fetch(url,{signal:AbortSignal.timeout(120000)});if(!r.ok)throw Error('Download returned '+r.status);if(Number(r.headers.get('content-length')||0)>max)throw Error('Oversized asset');const tmp=file+'.part';const fd=fs.openSync(tmp,'w');let total=0;try{for await(const chunk of r.body){total+=chunk.length;if(total>max)throw Error('Oversized stream');fs.writeSync(fd,chunk);}}finally{fs.closeSync(fd);}fs.renameSync(tmp,file);}
export async function update(c){validateConfig(c);chooseDevice(exec(c.adb,['devices','-l']),c.serial);fs.mkdirSync(c.workDir,{recursive:true});if(isForeground(c)){console.log('DEVICE_UPDATE_DEFERRED_FOREGROUND');return {status:'deferred_foreground'};}const lock=path.join(c.workDir,'update.lock');const fd=fs.openSync(lock,'wx');fs.writeFileSync(fd,JSON.stringify({pid:process.pid,time:new Date().toISOString()}));fs.closeSync(fd);try{
 const api='https://api.github.com/repos/'+c.repository;const releases=await json(api+'/releases?per_page=20');const candidates=releases.filter(r=>r.prerelease&&!r.draft&&/^v0\.1\.\d+-alpha\./.test(r.tag_name)&&r.assets.some(a=>a.name==='build-manifest.json'));
 if(!candidates.length){console.log('NO_ELIGIBLE_PRERELEASE');return {status:'no_release'};}
 const latest=candidates.sort((a,b)=>Date.parse(b.published_at)-Date.parse(a.published_at))[0];const manifestAsset=latest.assets.find(a=>a.name==='build-manifest.json');const dir=path.join(c.workDir,'releases',String(latest.id));fs.mkdirSync(dir,{recursive:true});await download(assetURL(manifestAsset.browser_download_url,c.repository),path.join(dir,'build-manifest.json'),100000);const m=readJSON(path.join(dir,'build-manifest.json'));
 if(m.repository!==c.repository||m.package!==c.package||m.sourceBranch!=='dev'||!/^\d+$/.test(String(m.workflowRun)))throw Error('Invalid release provenance');const run=await json(api+'/actions/runs/'+m.workflowRun);if(run.conclusion!=='success'||run.status!=='completed'||run.event!=='push'||run.head_branch!=='dev'||run.head_sha!==m.commit||run.path!=='.github/workflows/build.yml'||run.repository.full_name!==c.repository)throw Error('Release does not reference successful canonical dev build');
 const tag=await json(api+'/commits/'+encodeURIComponent(latest.tag_name));if(tag.sha!==m.commit)throw Error('Release tag/commit mismatch');const file=latest.assets.filter(a=>a.name===m.apk);if(file.length!==1||!m.apk?.match(/^[\w.-]+\.apk$/))throw Error('Expected exactly one matching APK');const previousFile=path.join(c.workDir,'installed.local.json');if(fs.existsSync(previousFile)){const previous=readJSON(previousFile);if(previous.originalSha256===m.sha256){console.log('DEVICE_UPDATE_ALREADY_CURRENT');return {status:'already_current'};}if(m.versionCode<=previous.versionCode)throw Error('Release version is not newer');}
 await download(assetURL(file[0].browser_download_url,c.repository),path.join(dir,m.apk),250*1024*1024);const result=await install(c,dir,m);writeJSON(path.join(c.workDir,'last-update-check.local.json'),{checkedAt:new Date().toISOString(),release:latest.tag_name,...result});return result;
 }finally{fs.unlinkSync(lock);}}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{const a=process.argv.slice(2);if(!a.includes('--config'))throw Error('Explicit --config required');await update(readJSON(a[a.indexOf('--config')+1]));}catch(e){console.error('UPDATE_BLOCKED: '+e.message);process.exitCode=1;}}
